#!/bin/bash
# https://stackoverflow.com/a/61110604
# https://stackoverflow.com/a/63092879
export DISPLAY=$(ip route | awk '/^default/{print $3; exit}'):0
export LIBGL_ALWAYS_INDIRECT=1
echo "export DISPLAY=$DISPLAY" >> ~/.session_env
echo "export LIBGL_ALWAYS_INDIRECT=1" >> ~/.session_env
